<?php
/**
 * Append-only, hash-chained document generation history stored through WC_Order.
 *
 * @package ITK_Commerce_Documents
 */

namespace ITK\Commerce\Documents;

defined( 'ABSPATH' ) || exit;

final class DocumentHistoryService {
    const META_KEY = '_itk_commerce_document_history';
    const MAX_ROWS = 200;

    /**
     * Append a generation/history event and return the new revision number for
     * the document type. The hash chain makes later accidental edits detectable.
     *
     * @param \WC_Order          $order Order.
     * @param string             $type Document type.
     * @param string             $number Stable document number.
     * @param string             $format html/pdf.
     * @param string             $content Generated bytes/text.
     * @param array<string,mixed> $context Additional bounded event context.
     * @return array<string,mixed>|\WP_Error
     */
    public function append( $order, $type, $number, $format, $content, array $context = array() ) {
        if ( ! $order instanceof \WC_Order ) {
            return new \WP_Error( 'itk_document_history_order', __( 'A valid WooCommerce order is required.', 'itk-commerce-documents' ) );
        }

        $history = $order->get_meta( self::META_KEY, true );
        $history = is_array( $history ) ? array_values( $history ) : array();
        $type = sanitize_key( $type );
        $revision = 1;
        foreach ( $history as $row ) {
            if ( is_array( $row ) && isset( $row['type'] ) && $type === $row['type'] ) {
                $revision = max( $revision, 1 + absint( $row['revision'] ?? 0 ) );
            }
        }

        $previous_hash = '';
        if ( ! empty( $history ) ) {
            $last = end( $history );
            $previous_hash = is_array( $last ) && isset( $last['entry_hash'] ) ? (string) $last['entry_hash'] : '';
        }

        $event = array(
            'event'         => isset( $context['event'] ) ? sanitize_key( $context['event'] ) : 'generated',
            'type'          => $type,
            'number'        => sanitize_text_field( $number ),
            'format'        => in_array( $format, array( 'html', 'pdf' ), true ) ? $format : sanitize_key( $format ),
            'revision'      => $revision,
            'created_at'    => gmdate( 'c' ),
            'actor_id'      => function_exists( 'get_current_user_id' ) ? max( 0, (int) get_current_user_id() ) : 0,
            'content_hash'  => hash( 'sha256', (string) $content ),
            'previous_hash' => $previous_hash,
        );

        if ( ! empty( $context['email_id'] ) ) {
            $event['email_id'] = sanitize_key( $context['email_id'] );
        }
        if ( ! empty( $context['note'] ) ) {
            $event['note'] = sanitize_text_field( $context['note'] );
        }

        $payload = wp_json_encode( $event, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
        $event['entry_hash'] = hash( 'sha256', $previous_hash . '|' . (string) $payload );
        $history[] = $event;

        if ( count( $history ) > self::MAX_ROWS ) {
            // Preserve the most recent audit window. The first retained row keeps
            // its previous hash so truncation is still visible to an auditor.
            $history = array_slice( $history, -self::MAX_ROWS );
        }

        $order->update_meta_data( self::META_KEY, $history );
        $order->save();
        return $event;
    }

    /** @param \WC_Order $order Order. @return array<int,array<string,mixed>> */
    public function all( $order ) {
        if ( ! $order instanceof \WC_Order ) {
            return array();
        }
        $history = $order->get_meta( self::META_KEY, true );
        return is_array( $history ) ? array_values( array_filter( $history, 'is_array' ) ) : array();
    }
}
