<?php
/**
 * WooCommerce order document renderer.
 *
 * @package ITK_Commerce_Documents
 */

namespace ITK\Commerce\Documents;

defined( 'ABSPATH' ) || exit;

final class DocumentService {
    /** @return string[] */
    public function types() {
        return array( 'invoice', 'delivery-note', 'return-form', 'packing-list' );
    }

    /**
     * Render a complete standalone HTML document.
     *
     * @param int    $order_id Order ID.
     * @param string $type Document type.
     * @return string|\WP_Error
     */
    public function render_html( $order_id, $type ) {
        $type = sanitize_key( $type );
        if ( ! in_array( $type, $this->types(), true ) ) {
            return new \WP_Error( 'itk_document_type', __( 'Unsupported document type.', 'itk-commerce-documents' ) );
        }

        $order = wc_get_order( absint( $order_id ) );
        if ( ! $order ) {
            return new \WP_Error( 'itk_document_order', __( 'Order was not found.', 'itk-commerce-documents' ) );
        }

        $label_map = array(
            'invoice'       => __( 'Invoice', 'itk-commerce-documents' ),
            'delivery-note' => __( 'Delivery note', 'itk-commerce-documents' ),
            'return-form'   => __( 'Return form', 'itk-commerce-documents' ),
            'packing-list'  => __( 'Packing list', 'itk-commerce-documents' ),
        );

        $language = (string) $order->get_meta( '_itk_commerce_language', true );
        $direction = in_array( strtolower( $language ), array( 'ar', 'fa', 'he', 'ur' ), true ) ? 'rtl' : 'ltr';
        $rows = '';
        foreach ( $order->get_items() as $item ) {
            $product = $item->get_product();
            $sku = $product ? $product->get_sku() : '';
            $rows .= '<tr><td>' . esc_html( $item->get_name() ) . '</td><td>' . esc_html( $sku ) . '</td><td>' . esc_html( (string) $item->get_quantity() ) . '</td>';
            if ( 'invoice' === $type ) {
                $rows .= '<td>' . wp_kses_post( $order->get_formatted_line_subtotal( $item ) ) . '</td>';
            }
            $rows .= '</tr>';
        }

        $billing = $order->get_formatted_billing_address();
        $shipping = $order->get_formatted_shipping_address();
        $address = in_array( $type, array( 'delivery-note', 'packing-list' ), true ) && $shipping ? $shipping : $billing;
        $total = 'invoice' === $type ? '<p class="total"><strong>' . esc_html__( 'Total', 'itk-commerce-documents' ) . ':</strong> ' . wp_kses_post( $order->get_formatted_order_total() ) . '</p>' : '';
        $return_fields = 'return-form' === $type ? '<div class="return-fields"><p>' . esc_html__( 'Reason for return:', 'itk-commerce-documents' ) . ' ______________________________</p><p>' . esc_html__( 'Customer signature:', 'itk-commerce-documents' ) . ' _____________________________</p></div>' : '';
        $price_heading = 'invoice' === $type ? '<th>' . esc_html__( 'Subtotal', 'itk-commerce-documents' ) . '</th>' : '';

        $html = '<!doctype html><html lang="' . esc_attr( $language ?: 'en' ) . '" dir="' . esc_attr( $direction ) . '"><head><meta charset="utf-8"><title>' . esc_html( $label_map[ $type ] ) . '</title><style>body{font-family:Arial,sans-serif;color:#222;margin:32px}.head{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #222;padding-bottom:16px}.meta{margin:22px 0;display:grid;grid-template-columns:1fr 1fr;gap:24px}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:start}.total{text-align:end;font-size:18px}.return-fields{margin-top:40px;line-height:2}.footer{margin-top:48px;font-size:12px;color:#666}@media print{body{margin:12mm}}</style></head><body>';
        $html .= '<div class="head"><div><h1>' . esc_html( $label_map[ $type ] ) . '</h1><p>' . esc_html( get_bloginfo( 'name' ) ) . '</p></div><div><strong>#' . esc_html( $order->get_order_number() ) . '</strong><br>' . esc_html( wc_format_datetime( $order->get_date_created() ) ) . '</div></div>';
        $html .= '<div class="meta"><div><strong>' . esc_html__( 'Customer', 'itk-commerce-documents' ) . '</strong><br>' . wp_kses_post( $address ) . '</div><div><strong>' . esc_html__( 'Order status', 'itk-commerce-documents' ) . '</strong><br>' . esc_html( wc_get_order_status_name( $order->get_status() ) ) . ( $language ? '<br><strong>' . esc_html__( 'Language', 'itk-commerce-documents' ) . ':</strong> ' . esc_html( $language ) : '' ) . '</div></div>';
        $html .= '<table><thead><tr><th>' . esc_html__( 'Product', 'itk-commerce-documents' ) . '</th><th>' . esc_html__( 'SKU', 'itk-commerce-documents' ) . '</th><th>' . esc_html__( 'Quantity', 'itk-commerce-documents' ) . '</th>' . $price_heading . '</tr></thead><tbody>' . $rows . '</tbody></table>' . $total . $return_fields;
        $html .= '<div class="footer">' . esc_html__( 'Generated by IT-Kayali Commerce Documents.', 'itk-commerce-documents' ) . '</div></body></html>';

        /**
         * Filter final document HTML.
         *
         * @param string    $html Document HTML.
         * @param \WC_Order $order Order.
         * @param string    $type Document type.
         */
        return (string) apply_filters( 'itk_commerce_document_html', $html, $order, $type );
    }

    /**
     * Return PDF bytes when a renderer is available. Dompdf is supported when
     * installed by the host; a custom renderer can be supplied by filter.
     *
     * @param string $html HTML.
     * @return string|\WP_Error
     */
    public function render_pdf( $html ) {
        $custom = apply_filters( 'itk_commerce_documents_pdf_renderer', null, $html );
        if ( is_callable( $custom ) ) {
            $bytes = call_user_func( $custom, $html );
            return is_string( $bytes ) ? $bytes : new \WP_Error( 'itk_pdf_renderer', __( 'Custom PDF renderer returned invalid data.', 'itk-commerce-documents' ) );
        }

        if ( class_exists( '\Dompdf\Dompdf' ) ) {
            $dompdf = new \Dompdf\Dompdf( array( 'isRemoteEnabled' => false ) );
            $dompdf->loadHtml( $html, 'UTF-8' );
            $dompdf->setPaper( 'A4' );
            $dompdf->render();
            return $dompdf->output();
        }

        return new \WP_Error( 'itk_pdf_unavailable', __( 'No PDF renderer is installed. Install Dompdf or provide the itk_commerce_documents_pdf_renderer adapter.', 'itk-commerce-documents' ) );
    }
}
